scxml parser: fix compilation with GCC 6
Says GCC 6:

  src/scxml/qscxmlparser.cpp:394:103: error: ‘visibility’ attribute ignored [-Werror=attributes]
     Q_DECL_HIDDEN static void qt_static_metacall(QObject *_o, QMetaObject::Call _c, int _id, void **_a)
                                                                                                       ^

Just drop the attribute. The class in which this function
is defined is not exported, anyway.

Change-Id: I7826306adf9e2bc5c25eeafc328a9b38e902fc61
Reviewed-by: Lars Knoll <lars.knoll@theqtcompany.com>